### ISSUE TITLE
VS Code 

### ISSUE THREAD

**Issue by dmonder** [jstaf/onedriver#273] opened 2022-08-28 21:16 UTC
Running VS Code (`code file.ext`) within a OneDrive directory (`cd ~/OneDrive/src/dir`) fails with the following message:

   cannot open path of the current working directory: Permission denied

Expected VS Code to run. This fails whether specifying a file or a directory. 

Running VS Code from outside OneDrive (`cd ~`) executes VS Code (`code .`). Then the file can be opened using File -> Open and navigating to the same file. 

Note: Running VS Code from within a directory in OneDrive (`cd ~/OneDrive/src/dir`) and then running VS Code with a directory outside of OneDrive (`code ~`) fails with the same error as above.

Running OneDriver v0.12.0 on Ubuntu 22.04.1 with VS Code 17.0.2 (Snap).

**Comment by dmonder** [comment] 2022-08-29 13:29
It seems the only problem is that I cannot run VS Code in the OneDrive folder itself (`cd ~/OneDrive/src/dir; code .`). I tested another Snap program (`htop`) and that has the same error. I am able to run VS Code outside of the OneDrive directory structure and even open a folder with the OneDrive without issue.

**Comment by Fourier33** [comment] 2023-06-26 18:14
Hi sir, I exactly met the same probelm. Do you find a way to solve it?

**Comment by dmonder** [comment] 2023-06-27 17:51
I have not tested this in a while. Running VS Code outside the OneDrive directory structure always worked for me. Inconvenient but it worked.

**Comment by Fourier33** [comment] 2023-06-27 20:12
I see. It seems I need to live with it. Thanks so much!

**Comment by jstaf** [comment] 2023-06-28 04:21
I think this is a problem with Snaps and Snap sandboxing (here's a similar issue with the Firefox snap and sshfs (another FUSE filesystem): https://askubuntu.com/questions/1465752/fuse-mounted-filesystems-and-snap-applications). 

When you use VSCode installed natively (.deb or .rpm packaging), cd-ing into the filesystem and doing `code .` works just fine. 

Going to close this as "wontfix" for now - the issue is with the Snap package and its sandboxing - it's something that will need to be solved on the Snap-side of things to allow it access to FUSE filesystem mounts.

**Closed by jstaf** 2023-06-28 04:21 UTC
