### ISSUE TITLE
No support for symlink

### ISSUE THREAD

**Issue by rioxrenato** [jstaf/onedriver#218] opened 2021-12-16 04:50 UTC
Please, implement symlink support

**Comment by jstaf** [comment] 2021-12-16 06:20
To make a long story short, OneDrive itself does not currently support symbolic links (or anything like them). I'm waiting until OneDrive implements this functionality before I can support symbolic links.

Going to close this as a duplicate of https://github.com/jstaf/onedriver/issues/80.

**Closed by jstaf** 2021-12-16 06:20 UTC
