### ISSUE TITLE
Files are locked after restart?

### ISSUE THREAD

**Issue by NZKea** [jstaf/onedriver#79] opened 2020-05-17 23:40 UTC
Trying to open a powerpoint stored on onedrive with wps office. The first time it is opened it works fine, but after a reboot when I try to open it a message appears "Document has been locked by username, do you want to open as read only".

![image](https://user-images.githubusercontent.com/20099289/82162737-dde15700-98fa-11ea-9c30-153c6ab6d9dc.png)

I am online and installed from the releases page. I have not got it launching on startup yet, rather just open the app first.

Any help with how to fix this would be appreciated!

**Comment by NZKea** [comment] 2020-05-17 23:48
Okay, looking at it seems that it may be only with that folder. Another folder with files is absolutely fine even after a restart. So looks like something has gone wrong with that particular set of files. The only thing I can think of is maybe I tried to open while onedriver had not launched.

**Comment by jstaf** [comment] 2020-05-18 19:14
Hi @NZKea I think this is the same issue as in https://github.com/jstaf/onedriver/issues/48. You should be able too open it in read-only mode then pick "edit anyway".

The root of the issue is that some applications create "lockfiles" (just a temporary, hidden file) to prevent multiple people from editing the file at once. This file gets created when you're editing the file and removed once you close it. Currently this lockfile gets its modification time updated after uploading the lockfile to the server and I don't think Microsoft Office or LibreOffice like it when this happens (and give you the warning you're seeing).

The issue should be solved in a future release, but for now, let me know if the workaround above works for you.

**Closed** 2020-05-20 03:35 UTC

**Comment by jstaf** [comment] 2020-06-05 22:43
So I know this issue is closed now, but this should now be solved as of #84
