### ISSUE TITLE
Files are download incompletely

### ISSUE THREAD

**Issue by chenxiex** [jstaf/onedriver#103] opened 2021-01-24 10:25 UTC
I tried to copy a video from the folder mounted by onedriver to a local folder using "cp" command. However, when the command finished, I found the video was incomplete. It's much smaller than the one on onedrive and I can only play a little part of it.

**Comment by jstaf** [comment] 2021-01-28 03:51
Yep, this is definitely a bug. Do any errors show up in the onedriver logs? (You can check these with `journalctl --user -u $SERVICE_NAME` - see the readme for what to use for `$SERVICE_NAME`.)

Just out of curiosity, how large was the original video?

**Comment by chenxiex** [comment] 2021-01-29 12:17
> Yep, this is definitely a bug. Do any errors show up in the onedriver logs? (You can check these with `journalctl --user -u $SERVICE_NAME` - see the readme for what to use for `$SERVICE_NAME`.)
> 
> Just out of curiosity, how large was the original video?

Thanks for your reply. This is the last error massage:
`onedriver[2351]: time="2021-01-29T20:08:09" level=error msg="Error during delta fetch, marking fs as offline." func="000041:fs.(*Cache).DeltaLoop()" file="delta.go:29" err="Get https://graph.microsoft.com/v1.0/me/drive/root/delta?token=aTE09NjM3NDc1MDY5MjU2MjM7SUQ9MTNGOTFCRjE0QTZGQTE4OCExMDE7TFI9NjM3NDc1MTg3MzEzMzc7RVA9MjA7U0k9Njc7RExFUD0wO1NHPTE7U089NjtQST0z: dial tcp: lookup graph.microsoft.com on 8.8.8.8:53: dial udp 8.8.8.8:53: connect: network is unreachable"`
The video is 122 MB.
Maybe that's because my network is not very stable. I think what I need is a resume function.

**Comment by jstaf** [comment] 2021-03-19 02:14
Hey sorry for the ultra-late reply - in this case, if you try to reopen the file on onedriver, it should re-download it because the checksum of the incompletely downloaded file doesn't match what its supposed to be. In this case the error `dial tcp: lookup graph.microsoft.com on 8.8.8.8:53: dial udp 8.8.8.8:53: connect: network is unreachable` indicates that the cause of the incomplete download was your network disconnecting, which onedriver can't really work around aside from re-downloading things again. (I'm going to close this one because it's caused by the network disconnecting, which isn't a bug in onedriver)

**Closed by jstaf** 2021-03-19 02:14 UTC
