### ISSUE TITLE
Deepin PPA unavailible

### ISSUE THREAD

**Issue by xiaodl813** [jstaf/onedriver#97] opened 2020-09-30 06:06 UTC
I'm using Deepin 20 as my Linux PC. But when I using PPA commend in the commend line, it tells me that "Error: could not find a distribution template for Deepin/n/a". So I have to download the old version in the release. May I have a latest version in release in the near future? Thank you!

**Comment by jstaf** [comment] 2020-09-30 16:02
Let me look into it and I'll see what the issue is.

**Comment by xiaodl813** [comment] 2020-10-01 04:23
> Let me look into it and I'll see what the issue is.

Thanks a lot!

**Comment by jstaf** [comment] 2020-10-02 21:48
Hi @xiaodl813, I think I found a solution for you (this describes the same error you are running into): https://wiki.deepin.org/wiki/Package_management#Error_when_add_PPA_repository

However, you'll want to make one change - the wiki article refers to a very old version of Ubuntu and you'll need to update to the new version - I've provided some updated instructions here (the main change is changing `quantal` to `focal` (Deepin 20 is roughly equivalent to Ubuntu 20.04 "Focal Fossa"):

Edit this file `gedit/usr/share/python-apt/templates/LinuxDeepin.info`:

```
sudo gedit /usr/share/python-apt/templates/LinuxDeepin.info
```

Add the following to the end (I've changed the relevant fields):

```
    Suite: focal
    RepositoryType: deb
    BaseURI: http://packages.linuxdeepin.com/deepin/
    MatchURI: packages.linuxdeepin.com
    MirrorsFile-amd64: LinuxDeepin.mirrors
    MirrorsFile-i386: LinuxDeepin.mirrors
    Description: Linux Deepin 20.04 'Focal'
    Component: main
    CompDescription: Officially supported
    CompDescriptionLong: Deepin-supported Open Source Software
    Component: non-free
    CompDescription: Restricted software
    CompDescriptionLong: Software restricted by copyright or legal issues
```

Let me know if this solves the issue for you!

There are two other options for you if you're still having trouble installing things:

* You can directly download and install the onedriver package from here: https://launchpad.net/~jstaf/+archive/ubuntu/onedriver/+files/onedriver_0.9.2-1_amd64.deb
* You can build the .deb package from source by following the instructions: https://github.com/jstaf/onedriver/blame/master/README.md#L156-L161

**Comment by xiaodl813** [comment] 2020-10-04 10:06
Thanks a lot!
I have installed the 0.9.2-1 version by using the link above successfully.
However, the attempt of adding PPA failed again. The solution based on Deepin Wiki is outdate. In the latest Deepin OS, there is no file called "LinuxDeepin.info" and "LinuxDeepin.mirrors". Instead, there are files called "Deepin.info" and "Deepin.mirrors". I tried to add the code above into Deepin.info, but it tells me the same error prompt as this issue begin. :(

**Comment by xiaodl813** [comment] 2020-10-04 10:16
I guess that it may caused by the Deepin OS itself.
I tried to build some softwares these days. And I always find that some libraries conflict with others. Once I force to update some libraries and then my desktop disappeared. After hours check, I guess the Deepin itself (or DDE) depends on many outdate libraries while the software I'm building is depending on newer ones.
And worsely, the conflict libraries are always underlying library, like libc6. It' s not easy to update. :(

**Comment by chenxiex** [comment] 2021-01-24 07:00
I met the same problem now, and I found a solution. Since the Deepin OS is based on debian, it's easy to add a debian source to Deepin. So I just visit [https://launchpad.net/~jstaf/+archive/ubuntu/onedriver/](url) and found the source in this page, then add them to sources.list and add the pub_key using apt-key. After that, I can install onedriver normally.

**Comment by jstaf** [comment] 2021-05-16 05:18
Note to self: add instructions for Deepin/non-Ubuntu distros to the readme file.

**Comment by jstaf** [comment] 2022-01-25 03:47
There are Debian-specific builds for awhile now at https://software.opensuse.org/download.html?project=home%3Ajstaf&package=onedriver, I'm going to close this one out.

**Closed by jstaf** 2022-01-25 03:47 UTC
