### ISSUE TITLE
G_TLS_CERTIFICATE_GENERIC_ERROR when connecting to account.live.com

### ISSUE THREAD

**Issue by edwkmho** [jstaf/onedriver#177] opened 2021-10-13 07:35 UTC
I am unable to get the app to connect to my onedrive. when tried to connect its giving out message of "Unacceptable TLS certificate"
![Onedriver-error-2021-10-13 15-07-45](https://user-images.githubusercontent.com/13256633/137087595-706e8641-496e-4704-9e7e-41134759bcf2.png)

I am unable to get to this page: 

![onedrive-permissions](https://user-images.githubusercontent.com/13256633/137103189-686eb1cf-78aa-40bd-865b-ed38e5b01678.png)

The app installed from COPR with the following command :
sudo dnf copr enable jstaf/onedriver
sudo dnf install onedriver

My system :
OS : Fedora 35 beta - Kernel v5.14.11-300
DE : Gnome v41
GPU - intel 4th i7
Ram : 32Gb
SSD: 250Gb

Please help. Thanks.

**Comment by edwkmho** [comment] 2021-10-17 08:15
dear jstaf, thanks for your prompt respond.

I am not connecting thru any VPN, direct to the ISP.

Below is the result of the curl command:
[edward@fedora ~]$ curl -Iv https://login.microsoftonline.com
*   Trying 20.190.144.162:443...
* Connected to login.microsoftonline.com (20.190.144.162) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; CN=stamp2.login.microsoftonline.com
*  start date: Sep  2 00:00:00 2021 GMT
*  expire date: Sep  2 23:59:59 2022 GMT
*  subjectAltName: host "login.microsoftonline.com" matched cert's "login.microsoftonline.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> HEAD / HTTP/1.1
> Host: login.microsoftonline.com
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Cache-Control: no-store, no-cache
Cache-Control: no-store, no-cache
< Pragma: no-cache
Pragma: no-cache
< Content-Length: 154706
Content-Length: 154706
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Expires: -1
Expires: -1
< Strict-Transport-Security: max-age=31536000; includeSubDomains
Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< Link: <https://aadcdn.msauth.net>; rel=preconnect; crossorigin
Link: <https://aadcdn.msauth.net>; rel=preconnect; crossorigin
< Link: <https://aadcdn.msauth.net>; rel=dns-prefetch
Link: <https://aadcdn.msauth.net>; rel=dns-prefetch
< Link: <https://aadcdn.msftauth.net>; rel=dns-prefetch
Link: <https://aadcdn.msftauth.net>; rel=dns-prefetch
< X-DNS-Prefetch-Control: on
X-DNS-Prefetch-Control: on
< P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
< x-ms-request-id: ded46b24-65d9-4729-92d9-c225c0b05e00
x-ms-request-id: ded46b24-65d9-4729-92d9-c225c0b05e00
< x-ms-ests-server: 2.1.12158.6 - KRSLR1 ProdSlices
x-ms-ests-server: 2.1.12158.6 - KRSLR1 ProdSlices
< Set-Cookie: fpc=AoyPal9ZHIZPgv_5t7eU8LY; expires=Tue, 16-Nov-2021 08:03:05 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: fpc=AoyPal9ZHIZPgv_5t7eU8LY; expires=Tue, 16-Nov-2021 08:03:05 GMT; path=/; secure; HttpOnly; SameSite=None
< Set-Cookie: esctx=AQABAAAAAAD--DLA3VO7QrddgJg7WevrWV-N0TjM7tsgFgZqDh75GeL4bYGG91CS7Bwn8cQUx72SS_Ynh-PVom9xPhBKHDJMi11W8_1SZOlW_OwUDojsBynIoMfuxgUTvgctD-m4mIobTmxJf-SeRT0Hw-WqkY40U7B0CKLIZ-_AGh2ShrqsGpcwg17TAEmNZyN0b-OYBY8gAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: esctx=AQABAAAAAAD--DLA3VO7QrddgJg7WevrWV-N0TjM7tsgFgZqDh75GeL4bYGG91CS7Bwn8cQUx72SS_Ynh-PVom9xPhBKHDJMi11W8_1SZOlW_OwUDojsBynIoMfuxgUTvgctD-m4mIobTmxJf-SeRT0Hw-WqkY40U7B0CKLIZ-_AGh2ShrqsGpcwg17TAEmNZyN0b-OYBY8gAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None
< Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
< Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
< Date: Sun, 17 Oct 2021 08:03:05 GMT
Date: Sun, 17 Oct 2021 08:03:05 GMT

< 
* Connection #0 to host login.microsoftonline.com left intact


Hopefully this help you to solve the issue. Many thanks.

**Comment by tomassplatch** [comment] 2021-11-02 07:32
Hello, I have exactly the same problem on Fedora 35 final.

**Comment by Sh1roKaze** [comment] 2021-11-09 22:50
I am also having this issue on Fedora 35.

**Comment by jstaf** [comment] 2021-11-21 17:28
I was finally able to reproduce this - the error only happens for personal accounts on initial app authorization (which only needs to happen a single time for an account). Using the headless version to authenticate works as a workaround because it only needs to be done once to authorize the "onedriver" app irrespective of how many computers you use it on.

Should be fixed soon :crossed_fingers:

**Comment by Sh1roKaze** [comment] 2021-11-21 20:32
Yes, after building the headless version and doing the initial authorization from there I got it to work. Thanks.

**Comment by jstaf** [comment] 2021-11-23 23:17
Preliminary fix in https://github.com/jstaf/onedriver/pull/208. Probably need to file a bug report with upstream (it looks like the Epiphany web browser has the same problem as well)... it appears to be glib/glib-networking (we're getting G_TLS_CERTIFICATE_GENERIC_ERROR for this cert only).

**Comment by jstaf** [comment] 2021-11-25 01:15
Bug opened upstream https://gitlab.gnome.org/GNOME/glib-networking/-/issues/180

**Comment by jstaf** [comment] 2021-11-29 04:09
There's a fix in #208. This appears to be a problem with Fedora 35's crypto policies https://bugzilla.redhat.com/show_bug.cgi?id=2024296, but the fix will let things keep working in the meantime.

**Closed by jstaf** 2021-11-29 04:09 UTC

**Comment by sthenley** [comment] 2022-02-02 04:24
Another workaround (Fedora 35):

sudo update-crypto-policies --set LEGACY 
# Do your thing: conect your MS account
sudo update-crypto-policies --set DEFAULT

**Comment by anulogarantias** [comment] 2022-03-03 02:40
> Another workaround (Fedora 35):
> 
> `sudo update-crypto-policies --set LEGACY `
> 
> Do your thing: conect your MS account..
> 
> `sudo update-crypto-policies --set DEFAULT`

This solved the issue for me. Thank you very much.
