### ISSUE TITLE
Problem with Office 365 (?)

### ISSUE THREAD

**Issue by coxackie** [jstaf/onedriver#1] opened 2019-02-10 11:07 UTC
Hi there, and many thanks for this. It works pretty well for a simple Microsoft account, but when I try to connect to a 365 account, I get:
```
(process:6962): libsoup-WARNING **: 11:01:47.797: gssapi step failed: Unspecified GSS failure.  Minor code may provide more information: SPNEGO cannot find mechanisms to negotiate
```
and then
```
2019/02/10 11:02:10 OpenDir("/")
2019/02/10 11:02:10 Auth tokens expired, attempting renewal...
```
Any ideas?

**Comment by jstaf** [comment] 2019-02-16 03:14
Hi, great to hear from you! Just out of curiosity, is this an organizational account like at a university or business? Or is this an account that you get from upgrading a Microsoft account to an Office365 subscription? 

The reason I ask is that Microsoft has a few different authentication "flows" and APIs for different types of accounts. So far the only authentication "flow" that's implemented is the Microsoft Graph one (this handles all of the stuff for Microsoft accounts). Right now I have a feeling that Microsoft is redirecting the authentication request to an organizational auth page that uses Kerberos or NTLM, which causes the request we're making [here](https://github.com/jstaf/onedriver/blob/d27bf78c8774462bee1d38e743c75dbe474ad75c/graph/oauth2.go#L62) to fail. 

I was able get a similar error from an organizational account just now, is this what you're seeing?:

```
# its an endless loop of this
2019/02/15 22:04:18 OpenDir("/")
2019/02/15 22:04:18 Auth tokens expired, attempting renewal...
2019/02/15 22:04:19 InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217
```

Also, a disclaimer: this is still under development and a lot of stuff doesn't work yet. At the time I type this, changes to files will not be uploaded back to Onedrive - writes are local only right now.

**Comment by jstaf** [comment] 2019-02-16 04:06
I've added better debugging in the latest version, please let me know what error you see in the log when you get the chance.

**Comment by coxackie** [comment] 2019-02-16 08:38
Thanks for the clarifications. Yes, it is a university organizational account, which most probably answers why there is a problem. With the new build, after trying to authenticate I get:
```
Failed to retrieve access tokens. Response from server:
{"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: 55579a96-5168-4a62-beee-f44072d50500\r\nCorrelation ID: b0fe7be8-4f50-4db6-b280-905afc06fca0\r\nTimestamp: 2019-02-16 08:32:19Z","error_codes":[9002313],"timestamp":"2019-02-16 08:32:19Z","trace_id":"55579a96-5168-4a62-beee-f44072d50500","correlation_id":"b0fe7be8-4f50-4db6-b280-905afc06fca0"}
```
Not sure how helpful this is.

 Many thanks again for your work. I understand it is very much WIP - I will try to test it as it goes.

**Comment by jstaf** [comment] 2019-02-16 21:51
Ok yep, same error. It could be a couple things, but I think the issue is likely that the app needs to request additional permissions for organizational accounts. I'll have to check though, there are a few other things it could be. (Debugging the authentication errors is really tough - all of the responses when something wrong happens are super vague.)

I'll check back here once I've made more progress on this one.

**Comment by jstaf** [comment] 2019-02-18 02:25
Ok solved it - the application wasn't expecting the `_` character during part of the authentication process, and that was throwing things off. Anyhow, should be fixed now - let me know if you run into any more issues!

**Closed by jstaf** 2019-02-18 02:25 UTC
