### ISSUE TITLE
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by dipunm** [jstaf/onedriver#263] opened 2022-06-15 01:17 UTC
I noticed recently that my file was not being updated, and so I deleted and tried to re-upload it. It wouldn't show up on the website.

I ran the app from the commandline and saw the following error:
```
02:14:15 WRN Upload session failed, will retry from beginning. error="small upload failed: Put \"https://graph.microsoft.com/v1.0/me/drive/items/6BB5F08A4543F2AC%215359:/File.txt:/content\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" id=local-V7RejsGNhi3E6olId9IL name=File.txt
```

**Comment by jstaf** [comment] 2022-07-04 02:10
I've seen this error off and on over the years, but have never quite been able to pin down what's causing it. My suspicion is that it's a network error caused by not getting a response back from Microsoft in 15 seconds (Microsoft's servers might be having a hard time), but admittedly this is total speculation.

Do you have a good way of reliably reproducing this?

Related: https://github.com/jstaf/onedriver/issues/98

**Comment by jstaf** [comment] 2022-07-10 21:05
Going to close this as a duplicate of #98.

**Closed by jstaf** 2022-07-10 21:05 UTC
