### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by vpont** [jstaf/onedriver#156] opened 2021-08-10 10:05 UTC
Would it be possible to add support for an ignore list, which would not sync the files and directories listed (similar to the `.gitignore`) or some other mechanism that allows this?

I.e: `.odignore`
```
.Trash-1000
.xdg-volume-info
```

Thank you and keep up the good work!

**Comment by jstaf** [comment] 2021-08-11 04:14
Going to close this one as a duplicate of #102. An ignore list from a .gitignore-like file was along the lines of what I was thinking of doing actually!

However, there is one caveat... you will *never* be able to ignore either the `.xdg-volume-info` or the `.Trash-####` directory. `.xdg-volume-info` is used to label the drive and assign it an icon in various file browsers like Nautilus. Likewise, most desktop environments will start creating error popups every time you delete a file and you lose the ability to trash/restore files if the `.Trash-####` folder is missing/ignored. (I only know this because I actually did add both of these files to an ignore list in very early versions of the filesystem and it broke the trash functionality.)

It would be nice to maybe map the `.Trash-####` folder to the OneDrive Recycle Bin at some point, but Microsoft does not currently expose the Recycle Bin APIs: https://github.com/OneDrive/onedrive-api-docs/issues/1212#issue-550528827

**Closed by jstaf** 2021-08-11 04:14 UTC
