### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by wondercomm** [jstaf/onedriver#167] opened 2021-08-27 03:51 UTC
Hi, 

Thank you for making this amazing application. It prevented me from moving to windows. :) 

1. How can someone donate to you? 
2. Will you be adding support for Sharepoint as well? _This is the only thing missing from my workflow._

_ I had initially installed the package using this link --> [here](https://launchpad.net/~jstaf/+archive/ubuntu/onedriver)
but today it stopped working on Pop!OS after they released an update. Good that I read through your instructions here, the OpenSUSE one worked perfectly!

Thanks!

**Comment by jstaf** [comment] 2021-12-16 06:25
1. There is support for donations via Github Sponsors now :slightly_smiling_face: 
2. Yes, I'm hoping to. Currently working on rewriting the GUI in Go (this way I can share code between the GUI and the filesystem itself), but after that I intend to add support for shared items and Sharepoint.

**Comment by t00** [comment] 2022-04-23 21:03
@jstaf Do you think Sharepoint support is doable soon? I happily chipped in for your great work.

Also I just had a look at go source code, set up VSCode debugging and while myself not being a go dev, it would be an interesting exercise to have a "Go" with adding Sharepoint stuff.

I guess new things are needed:

1. Change order of selecting a mount point swapped with selection of a OneDrive/Sharepoint share would help - user might not know upfront what shares are available for them thus what name of a local folder to pick
2. Sign in will likely remain unchanged, followed by a (new) selection of one of available Sharepoint shares - new APIs to enumerate shares available for the signed in user and UI to select them.
3. I have not looked at Sharepoint API but very likely drive identifiers will be different for Sharepoint yet rest of the sync logic will hopefully remain unchanged. Possibly even URL format is the same.

I checked logs of ExpanDrive (commercial app, buggy in regard to handling Sharepoint API and loses data) and API seems straightforward.

**Comment by abraunegg** [comment] 2022-04-23 21:21
@t00 
> I checked logs of ExpanDrive (commercial app, buggy in regard to handling Sharepoint API and loses data) and API seems straightforward.

SharePoint has many *odities* and inconsistencies. If you need a OneDrive Client that supports SharePoint in the meantime please look at https://github.com/abraunegg/onedrive as it fully supports SharePoint.

**Comment by t00** [comment] 2022-04-24 07:02
@abraunegg Thank you for putting me down-to-earth thinking it will be easy. I have seen your client but in my use case on-demand loading is a must considering amount of data to be accessed sporadically - sync is not an option unfortunately.

@jstaf I tried on-demand with a 500MB mp4 video and it did not work, VLC would freeze indefinitely even though file normally is downloaded from OneDrive in about 2-3 minutes

**Comment by jstaf** [comment] 2022-07-10 21:18
Closing this as the original ask (sharepoint support) is a duplicate of #107. For the on-demand videos (large file sizes), there are other issues in #200 and #257.

**Closed by jstaf** 2022-07-10 21:18 UTC
