### ISSUE TITLE
GUI hard to read switch state

### ISSUE THREAD

**Issue by studentmain** [jstaf/onedriver#256] opened 2022-05-21 20:58 UTC
![image](https://user-images.githubusercontent.com/80723249/169668621-c3e7d34b-3230-41cc-b35a-fe7d10c8e07b.png)

onedriver 0.12.0-1

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3

**Comment by jstaf** [comment] 2022-07-04 02:31
Going to close this one as a duplicate of this one #262. (Going to see if I can turn off the blue color for the selected row, or at least make it a little less intense for distros shipping a non-standard GTK theme.)

**Closed by jstaf** 2022-07-04 02:31 UTC
