### ISSUE TITLE
Files from Libreoffice Calc has been replaced by one with "0 byte"

### ISSUE THREAD

**Issue by Frcribeiro** [jstaf/onedriver#119] opened 2021-04-29 16:10 UTC
I was working and saved one calc file. When i restarted my PC and actived the Ondriver, the file was totaly erased and the type of file was changed to text file, but with "0 byte". I losted all information.

I made several tests, and the problem is happing when Ondriver synchronize... it is erasing documents.

I'm using Manjaro.

**Comment by jstaf** [comment] 2021-05-16 05:11
This is a duplicate of #99. Closing.

That said, I think the bug is now fixed if you build the latest version from the master branch. Try things out and feel free to reopen this if you still are seeing issues.

**Closed by jstaf** 2021-05-16 05:11 UTC
