### ISSUE TITLE
OneDrive Business some files are not shown in the directory

### ISSUE THREAD

**Issue by 0anton** [jstaf/onedriver#57] opened 2020-03-12 19:55 UTC
I noticed that some files from OneDrive Business folder with plain name like "Thursday Notes.txt" are not shown in the directory.

I tried to modify file over MS OneDrive webpage  and suddenly the file appeared in the listing. 

For file listing there is no spectacular in logs like:

`DEBU[2020-03-12T20:51:54]inode.go:244 001047:graph.(*Inode).Readdir()`

I compiled the most recent version of onedriver:

`onedriver v0.7.2 237b1613`

`fusermount version: 2.9.7`

**Comment by jstaf** [comment] 2020-03-12 23:52
I don't actually have a OneDrive Business account to test with, but you can jack up the logs to maximum vebosity with `--log trace` to see every single operation the filesystem will perform. (It's honestly a little too detailed.)

However: there was a bug before version 0.7.2 where the local cache was not being started up correctly on system boot and it may not have synced with your remote changes. This cache carries over between versions, and it's possible that your local cache still has some bad data from before 0.7.2 that's affecting directory listings (I know, this filesystem is supposed to be stateless...). Stop the filesystem and try wiping the cache with `onedriver -w` and see if the issue persists. This should solve your issue if I'm diagnosing things correctly.

**Comment by 0anton** [comment] 2020-03-13 10:15
Hi Jeff,

Actually, I reset cache several times in a hope the file will reappear...
I'll let you know if I find anything useful.

Anton

**Comment by jstaf** [comment] 2020-03-18 02:22
Hi @0anton I was able to snag a OneDrive for Business developer account (setting it up now) - do you have instructions on how to reproduce this bug?

**Comment by 0anton** [comment] 2020-03-19 11:56
Hi Jeff,

Unfortunately, I cannot tell how to reproduce the problem. My steps were:
1. I created the text file (a short note written in the text editor) in the folder with another 100+ other text files, which is synced over OneDrive Business. It was a Windows host.
2. I saw the file appeared on the web version of OneDrive Business.
3. The file was not shown in the folder with the onedriver client (restarts, re-auth, cache reset made). All other text files in the dir were shown.
4. I tried to update file on locally on the windows host - web version is updated, but file is still not shown in the onedriver.
5. I tried to use [Insync](https://www.insynchq.com/i/onedrive) and it synced ALL files, included the affected one.
6. I tried to modify affected text file from Onedrive online editor (just did some non substantial change) and saved the file. The file appeared on ondriver folder!
7. I changed the file again from the windows host locally using text editor (added one letter) and the file disappeared again in onedriver mounted folder.

File has a non-spectacular name: 'Thursday Notes.txt".

In Insync folder:

```
~/OneDriveBusiness2/Documents/_work_notes$ ls -lt "Thursday Notes.txt"
-rw-r--r-- 1 d057039 sap_users 90 Mär 13 12:37 'Thursday Notes.txt'
```

In onedriver mounted folder:

```
~/OneDriveBusiness/Documents/_work_notes$ ls -lt "Thursday Notes.txt"
ls: cannot access 'Thursday Notes.txt': No such file or directory
```


Hope it helps.


Kind regards,
Anton

**Comment by jstaf** [comment] 2020-03-24 01:35
I managed to reproduce the issue. It turns out the method of listing files I was using was capped at a max of 200 files in a directory. Any extra files past 200 were not getting synced by the client. Anyhow, just wanted to say nice find! The fix will be in the next release.

**Comment by jstaf** [comment] 2020-03-24 03:39
Ok, bug should be fixed on the master branch as of #62. Let me know if this fixes things for you!

**Comment by jstaf** [comment] 2020-03-27 19:11
Hey @0anton I'm going to close this out for now. Please reopen this issue if you notice that this is still causing issues after building from the master branch.

**Closed by jstaf** 2020-03-27 19:11 UTC

**Comment by 0anton** [comment] 2020-03-30 07:01
Thank you for the fix Jeff! Great finding! I'll rebuild, test and let you know if it solved the issue for me. We can keep an issue closed for now.
