### ISSUE TITLE
Allow renaming mounted drive in file manager

### ISSUE THREAD

**Issue by SilverMarcs** [jstaf/onedriver#146] opened 2021-07-08 11:55 UTC
My school email is huge and it takes that as name for mounted drive in nautilus file manager and also disallows reducing sidebar size. Would it be possible to rename the drive?

**Comment by jstaf** [comment] 2021-07-09 04:31
Yes, it's actually getting the drive name from the hidden `.xdg-volume-info` file. Just edit the file (the `Name=` part) and it will change the name of the drive. onedriver should respect the new drive name once you rename it.

**Comment by SilverMarcs** [comment] 2021-07-09 07:27
> Yes, it's actually getting the drive name from the hidden `.xdg-volume-info` file. Just edit the file (the `Name=` part) and it will change the name of the drive. onedriver should respect the new drive name once you rename it.

Where exactly is this file? Sorry Im new to this stuff couldn't find much googling

**Comment by jstaf** [comment] 2021-07-09 20:10
Ah, it'll be in the root directory of the OneDrive mountpoint. So if you've mounted OneDrive at `~/OneDrive` the file will be at `~/OneDrive/.xdg-volume-info`

**Comment by SilverMarcs** [comment] 2021-07-09 20:52
> Ah, it'll be in the root directory of the OneDrive mountpoint. 
Haha looked  everywhere but there. Thanks, great app!

**Comment by jstaf** [comment] 2021-07-16 23:36
I'm going to close this one out because it sounds like the issue is solved :slightly_smiling_face: 

Glad to hear you like the app!

**Closed by jstaf** 2021-07-16 23:36 UTC
