### ISSUE TITLE
cannot upload/make folders

### ISSUE THREAD

**Issue by wrtiap** [jstaf/onedriver#25] opened 2019-09-04 15:16 UTC
Hi, I don't understand why I seem to be the only one with this problem, but I can't figure out what I did incorrectly either in the installation or usage.
Other than in the home directory of my mounted OneDrive folder, every time I mkdir/vim a new folder/file or even try to edit a file like "libreoffice xxxx" or "vim xxxx" (read-only "less xxxx" works), onedriver immediately crashes and stops with: 
"- FATAL - 1:drive_item.go:70:NewDriveItem() - Parent or parent cache cannot be nil:"
last message before that is the creation of the files/folders, e.g.:
"- TRACE - 1:fusefs.go:316:Create() - "

Deleting files/folders seem to be fine though. Also, everything seems to work perfectly fine in the root directory of my OneDrive.

**Comment by jstaf** [comment] 2019-09-05 18:44
Try building things from the `delta` branch and let me know if that solves your issue. I can't guarantee how stable it is (it's my current dev branch and I sometimes break things there), but I recall seeing and fixing a similar bug there.

If you still see issues after rebuilding from the delta branch, let me know. Send me some instructions to reproduce things (`mkdir something; vim something/file.txt` etc, etc.) and the log with any information that's sensitive to you removed.

**Comment by wrtiap** [comment] 2019-09-07 18:22
Delta branch seems to work perfectly as far as I can tell! Thanks! Do I just close this issue now?

**Comment by jstaf** [comment] 2019-09-07 18:55
Yep, we can close it. Great to hear the issue is fixed! :)

(Also I've merged the current delta branch into master a little bit ago, so the improvements there are now the default.)

**Closed by jstaf** 2019-09-07 18:55 UTC
