### ISSUE TITLE
Does not have a release file

### ISSUE THREAD

**Issue by torspedia** [jstaf/onedriver#154] opened 2021-08-07 11:17 UTC
Just tried to download the app, onto Pop OS 21.04 but got the following message: "**The repository 'http://ppa.launchpad.net/jstaf/onedriver/ubuntu hirsute Release' does not have a Release file**."

I also got this message "**Unable to locate package onedriver**" when I went to the '_sudo apt install onedriver_' part of the process.

**Comment by jstaf** [comment] 2021-08-08 01:12
This is a duplicate of https://github.com/jstaf/onedriver/issues/141. 

(To make a long story short the package is only available for 20.04 right now... I need to add PPAs/prebuilt packages for the other Debian/Ubuntu versions.)

**Closed by jstaf** 2021-08-08 01:12 UTC
