### ISSUE TITLE
All files empty

### ISSUE THREAD

**Issue by ThorsenRune** [jstaf/onedriver#90] opened 2020-07-03 07:52 UTC
Hi, I started using onedriver with linux mint a month ago for backing up my files to onedrive. Seemed to work alright uploading the files. Now I needed to restore one and found that all files on onedrive had 0byte dimension.
Is this a known issue?

**Comment by jstaf** [comment] 2020-07-05 17:28
In onedriver versions 0.8 and earlier, shutting off your computer or otherwise stopping the filesystem before it had finished uploading files would permanently kill any uploads in progress (since the program doing the uploads was now dead). Any incompletely uploaded files at the time you shut off the program/computer would show up as a 0 byte file (creating this 0 byte placeholder file is the first step in the upload process). Unfortunately this wasn't exactly demonstrated well to the user - file browsers like GNOME's Nautilus would show files as fully copied to the OneDrive mountpoint, even if onedriver was still uploading those files in the background.

Anyhow, this has been fixed in onedriver versions 0.9+: turning off your computer/unmounting the filesystem will still stop any active uploads, but now they'll be restarted the next time you start onedriver. Check out the changelog here: https://github.com/jstaf/onedriver/releases

If you're still seeing 0 byte files on version 0.9.1+, let me know!

**Comment by ThorsenRune** [comment] 2020-07-06 07:58
Hi jstaf, thanks I see I have been using onedriver v0.9.0 fe22e1d6
I am on linux mint

**Comment by ThorsenRune** [comment] 2020-07-07 07:35
Did my backup yesterday. 
Today all files in the onedrive directory are zero. 
Im going to give up on this, but keep on the good work

**Comment by jstaf** [comment] 2020-07-08 00:00
Fair enough. Out of curiosity, what is the best way to reproduce the issue? (Also it would be helpful to see some of the logs.)

Are you using a backup procedure that looks something like: start onedriver, copy all files to mountpoint, stop onedriver? If this is the case, files are not going to be uploaded correctly - onedriver needs to remain on until the uploads complete. onedriver will recover any uploads that weren't completed from the last session, but still needs to remain on until the uploads finish (you won't have any files get uploaded if the program that's uploading them gets stopped prematurely). If you're uploading gigabytes of files, it may take upwards of 15-30 minutes for all uploads to complete depending on your upload speeds.

**Comment by jstaf** [comment] 2020-07-26 16:40
In lieu of a response, I'm going to close this issue out - feel free to reopen this issue with instructions to reproduce/logs if you want me to take another look at this.

**Closed by jstaf** 2020-07-26 16:40 UTC

**Comment by ThorsenRune** [comment] 2020-07-29 08:46
Hi, sorry for not replying timely. Yes thats the procedure. Copying all files to mountpoint. Working some hours and putting the PC in standby. Did not stop onedriver. Is that necessary? However the problem is that there is no indication of the status of upload/download as also directly using onedrive (as opposed to google drive - which works better). 
However as said, I give up on onedriver because reliable backup is critical.

**Comment by jstaf** [comment] 2020-07-31 03:36
Out of curiosity, did you have any unusual characters in your filenames (symbols or non-ASCII/non-English characters)? The version of onedriver you were using would fail to upload these files (this was fixed in 0.9.1). 

If you want to follow up on this and are able to reproduce the issue, please send me the logs (remove any information you feel is sensitive). The upload errors will be at the end of the logs.
