### ISSUE TITLE
Freeze issue

### ISSUE THREAD

**Issue by Miccio-AN** [jstaf/onedriver#150] opened 2021-07-25 14:53 UTC
First of all, thank you for your work!
I noticed this small/big problem: after installing Onedriver my PC refuses to go to sleep. 
I'm using Linux Mint latest version.
The system says that the related task refuses to freeze. What can I do?
Thank you!

**Comment by jstaf** [comment] 2021-07-26 22:15
I'll need to figure out why the system thinks it can't go to sleep - what desktop environment are you using? Cinnamon? I'm guessing that Cinnamon is trying to be nice to user processes while meanwhile KDE/GNOME just go to sleep/shutdown without paying attention to what's running. 

In the meantime, I suggest either unmounting the drive normally through the GUI or alternatively, you can just force quit/kill the onedriver process (it is safe to kill onedriver however you want).

**Comment by Miccio-AN** [comment] 2021-07-27 08:10
Thank you very much for the very fast response!

In fact, unmounting the drive before suspend the system, everything works regularly.
The PC in question is the only one I use with Mint and Cinnamon which (you're right!) seems to be too "gentle" :) in the other desktops I always have Debian with Gnome or Ubuntu even with Gnome. As soon as I can I'll try on those onedriver.

Thanks again for the reply. Have a nice day.

**Comment by jstaf** [comment] 2021-08-08 03:32
I tried to reproduce this using a fresh install from the Linux Mint 20.2 iso (I used the Cinnamon version) but couldn't reproduce the problem. I installed onedriver, left it running, and then tried shutting down/restarting/etc. ... in each case the system just shut down without issue.

Can you send me a screenshot of things / give me the last few minutes of logs? You can get the logs via:

```bash
# in this case $MOUNTPOINT is wherever you've mounted the drive, for instance: /home/username/OneDrive
export SERVICE_NAME=$(systemd-escape --template onedriver@.service --path $MOUNTPOINT)
journalctl --user --since '15 minutes ago' -u $SERVICE_NAME
```

**Comment by Miccio-AN** [comment] 2021-08-20 12:44
Hi, I'm sorry but as I said earlier Mint was using it on only one PC that I have currently replaced with Ubuntu. I can no longer report the problem. I mainly use Debian (10 and recently 11 bullseye) and Ubuntu on other machines. No problem. Thanks anyway for checking.

**Comment by jstaf** [comment] 2021-08-22 20:35
No worries. I'll close this one out for now, but don't hesitate to let me know if you run into any more issues.

**Closed by jstaf** 2021-08-22 20:35 UTC
